services:
  - type: web
    name: cityconnect-backend
    env: python
    buildCommand: pip install -r requirement.txt
    startCommand: gunicorn cityconnect.wsgi:application
    autoDeploy: true
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        sync: false
      - key: EMAIL_USE_TLS
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DEFAULT_FROM_EMAIL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: HF_API_KEY
        sync: false
      - key: GOOGLE_MAPS_API_KEY
        sync: false